In [ ]:
#1. What is a Python library? Why do we use Python libraries?
# Python library is a collection of functions that can be reused

In [ ]:
#2. What is the difference between Numpy array and List?
# Numpy Array stores homogeneous data
#List stores heterogeneous data eg. combination of integers and string

In [1]:
import numpy as np

In [2]:
#3- Find the shape, size and dimension of the following array?
arr= np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [3]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [4]:
#Dimension
np.ndim(arr)

2

In [5]:
#Size
np.size(arr)

12

In [6]:
#Shape
np.shape(arr)

(3, 4)

In [7]:
#4. Write python code to access the first row of the following array?
arr[0]

array([1, 2, 3, 4])

In [8]:
#5 How do you access the element at the third row and fourth column from the given numpy array?
arr[2][3]

12

In [40]:
#6 Write code to extract all odd-indexed elements from the given numpy array?
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [42]:
arr[0:3, (1,3)]

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [10]:
#7 How can you generate a ran^om 3x3 matrix with values between 0 an^ 1?
arr1= np.random.randint(0,2, size=(3,3))

In [11]:
arr1

array([[1, 0, 0],
       [1, 0, 0],
       [0, 0, 1]])

In [12]:
type(arr1)

numpy.ndarray

In [13]:
np.matrix(arr1)

matrix([[1, 0, 0],
        [1, 0, 0],
        [0, 0, 1]])

In [14]:
# 2nd way for the above question
arr2=np.eye(3)

In [15]:
arr2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.matrix(arr2)

matrix([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [17]:
#8. Describe the difference between np.random.rand and np.random.randn?
# The only difference between random.rand and random.randn is
# random.rand will give you only positive values
# random.randn will give you postive as well as negative

In [18]:
#9. Write co^e to increase the ^imension of the following array?
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
np.expand_dims(arr, axis=0)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [20]:
#10. How to transpose the following array in NumPy?
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
arr.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [34]:
#11 Consider the following matrix:

arr2=np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

arr3=np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [35]:
#Index wiLe multiplication
arr2*arr3

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [36]:
# Matrix multiplication
#This will not be possible as its not off n*n shape

In [37]:
#Add both the matrix
arr2+arr3

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [38]:
#Subtract matrix B from A
arr2-arr3

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [39]:
#Divide Matrix B by A
arr3/arr2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
#12.Which function in Numpy can be used to swap the byte order of an array?
#ndarray.byteswap

In [ ]:
#13.What is the significance of the np.linalg.inv function?
#Used to calculate the inverse of an matrix

In [43]:
#14. What does the np.reshape function do, and how is it used?
#np.reshape function reshapes the array into a given shape (rows, columns)

In [ ]:
#15. What is broadcasting in Numpy?
#Breoadcasting means ability of numpy to treat arrays with different dimensions